import React from "react";

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 sm:p-10 text-gray-800">
      <h1 className="text-4xl font-bold text-center mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-500 text-center mb-8">
        Last updated: February 24, 2025
      </p>

      <p className="mb-6">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mb-6">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the{" "}
        <a
          href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 underline hover:text-blue-700"
        >
          Free Privacy Policy Generator
        </a>
        .
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Interpretation and Definitions
      </h2>

      <h3 className="text-xl font-medium mt-6 mb-2">Interpretation</h3>
      <p className="mb-6">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        plural.
      </p>

      <h3 className="text-xl font-medium mt-6 mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-6 space-y-4">
        <li>
          <strong>Account:</strong> A unique account created for You to access
          our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate:</strong> An entity that controls, is controlled by,
          or is under common control with a party, where "control" means
          ownership of 50% or more of the shares, equity interest, or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li>
          <strong>Company:</strong> Refers to AI PDF Notes, referred to as "We,"
          "Us," or "Our" in this Agreement.
        </li>
        <li>
          <strong>Cookies:</strong> Small files placed on Your Device by a
          website, containing details of Your browsing history and other
          information.
        </li>
        <li>
          <strong>Country:</strong> Refers to Ontario, Canada.
        </li>
        <li>
          <strong>Device:</strong> Any device that can access the Service, such
          as a computer, cellphone, or digital tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> Information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> Refers to the Website.
        </li>
        <li>
          <strong>Service Provider:</strong> Any natural or legal person who
          processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Usage Data:</strong> Data collected automatically, either
          generated by the use of the Service or from the Service infrastructure
          itself (e.g., duration of a page visit).
        </li>
        <li>
          <strong>Website:</strong> Refers to AI PDF Notes, accessible from{" "}
          <a
            href="https://aipdf.vercel.app"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-500 underline hover:text-blue-700"
          >
            aipdf.vercel.app
          </a>
          .
        </li>
        <li>
          <strong>You:</strong> The individual accessing or using the Service,
          or the company/legal entity on behalf of which the individual is
          accessing or using the Service.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="text-xl font-medium mt-6 mb-2">Types of Data Collected</h3>
      <h4 className="text-lg font-medium mt-4 mb-2">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information, including:
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-medium mt-4 mb-2">Usage Data</h4>
      <p className="mb-6">
        Usage Data is collected automatically when using the Service. This
        includes information such as IP address, browser type, pages visited,
        time and date of visit, and other diagnostic data.
      </p>

      <h4 className="text-lg font-medium mt-4 mb-2">
        Tracking Technologies and Cookies
      </h4>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to analyze and improve
        Our Service. Types of cookies we use include:
      </p>
      <ul className="list-disc pl-6 space-y-4">
        <li>
          <strong>Necessary Cookies:</strong> Essential for providing basic
          functionality and preventing fraudulent use.
        </li>
        <li>
          <strong>Acceptance Cookies:</strong> Remember your consent to cookie
          usage.
        </li>
        <li>
          <strong>Functionality Cookies:</strong> Enhance user experience by
          remembering preferences like login details.
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
